message: Welcome to Ecommerce Platform DEV Environment
jwt:
  secret: 7e1f3f8a6c4d9b2e5a7f1c3d8e6b9f2a7c4d1e8f3a6b5c2d9e7f1a3c5b8d2e6

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  tracing:
    sampling:
      probability: 1.0

  endpoint:
    health:
      show-details: always

  prometheus:
    metrics:
      export:
        enabled: true

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level [${spring.application.name}] [traceId=%X{traceId}] - %msg%n"
