message: Cart Service DEV Environment

server:
  port: ${CART_SERVICE_PORT:8085}
  shutdown: graceful

spring:
  application:
    name: cart-service

  data:
    redis:
      host: one-bobcat-102440.upstash.io
      port: 6379
      username: ${REDIS_USERNAME:default}
      password: "{cipher}bab93dd88eb05a542c312ea1096cf187173b1999127c3ad7b6ff795e436a4030a966f90ba140432e1ec1cd4eaf88fed58267dc9ffb5b4d642fdde7d6acc720852058fdd8226ca27f847a395669875522"
      ssl:
        enabled: ${REDIS_SSL_ENABLED:true}

cart:
  ttl:
    days: ${CART_TTL_DAYS:7}

logging:
  level:
    root: INFO
    com.ecommerce.cart: INFO
    org.springframework.data.redis: INFO
