server:
  port: 8085

spring:
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_ISSUER_URI:http://localhost:8081}
          jwk-set-uri: ${AUTH_JWK_SET_URI:http://localhost:8081/oauth2/jwks}

cart:
  ttl:
    days: 7

springdoc:
  swagger-ui:
    path: /swagger-ui.html
