spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: test-route
              uri: http://httpbin.org
              predicates:
                - Path=/test/**
              filters:
                - RewritePath=/test/(?<segment>.*), /$\{segment}
