server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: ecommerce_user
    password: ecommerce_password

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true

grpc:
  server:
    port: 9090
