message: Order Service DEV Environment

server:
  port: ${ORDER_SERVICE_PORT:8086}
  shutdown: graceful

spring:
  application:
    name: order-service

  datasource:
    url: "{cipher}f4d59ad320f82748767bba5381b846a07d95b1ce2dce8881e316a731e120c1c2c3bc26309d70b068dfb7b1ef0650a8c25c93cd0a6db885e8a365ad19b8dbdb0526161e2a8415f68e34f182224805f48584beff3348136d5998bf9dc77ad0b587f3b24b21db4116e678946f0b14fb720c5d907d775e8b7d8922b79f81dca40056f1c58a947645cbdccedb4965bc481cc7"
    username: "{cipher}fdfd1690e7f381bf2cf4c5ec3c9c1d48fb12bb74af6d7f1d82a8b080f7bf62fd"
    password: "{cipher}079b62ce6f7cf6f6b0e3d08c1711ce51ca7c82b034f94f1e11c8ad874415e6314492f5e5fb0422d69475991910cfa6c7"
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}

    template:
      observation-enabled: true

    producer:
      client-id: ${ORDER_KAFKA_PRODUCER_CLIENT_ID:order-service-producer}
      acks: all
      retries: ${ORDER_KAFKA_PRODUCER_RETRIES:3}
      batch-size: ${ORDER_KAFKA_BATCH_SIZE:16384}
      buffer-memory: ${ORDER_KAFKA_BUFFER_MEMORY:33554432}
      compression-type: ${ORDER_KAFKA_COMPRESSION_TYPE:snappy}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

      properties:
        spring.json.add.type.headers: false
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
        delivery.timeout.ms: ${ORDER_KAFKA_DELIVERY_TIMEOUT_MS:120000}
        request.timeout.ms: ${ORDER_KAFKA_REQUEST_TIMEOUT_MS:30000}
        linger.ms: ${ORDER_KAFKA_LINGER_MS:5}

grpc:
  server:
    enabled: false

  clients:
    inventory:
      host: ${INVENTORY_GRPC_HOST:localhost}
      port: ${INVENTORY_GRPC_PORT:9091}
      deadline-ms: ${INVENTORY_GRPC_DEADLINE_MS:8000}
      plaintext: ${INVENTORY_GRPC_PLAINTEXT:true}

logging:
  level:
    root: INFO
    com.ecommerce.order: INFO
    org.springframework.kafka: INFO
    org.apache.kafka: WARN
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

order:
  default-currency: ${ORDER_DEFAULT_CURRENCY:INR}
