message: Order Service DEV Environment

server:
  port: ${ORDER_SERVICE_PORT:8086}
  shutdown: graceful

spring:
  application:
    name: order-service

  datasource:
    url: "{cipher}99408cb1cd93b4c0a54d7aa15ca6c576fb72a6abbf27825ae2f44635e6175cac745c54a769af6313444cdc082f1c7b43b9cc7156795bd6b1d63c65d23e9a40de6354f670fa93ea30ad555372889646c6bbb2d065686d8d44fa1c42d5054771e5ff3cc86e884829ce1a4ecbabe488c7cf7a6bcb208c48c2982d79c8953522f641dcc813aebc898424af51e6a53a8e7ed6"
    username: "{cipher}1bce5867ddb274959cc9b09c32dd0c6de96aab14a339fe1bd28094c9bde18665"
    password: "{cipher}30a6d4b3c8dc1762530b4f46320908f290bacbd303396d41c7607ff8f07faeee0c1e638c3a8450d6633396b5b833feb4"
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}

    template:
      observation-enabled: true

    producer:
      client-id: ${ORDER_KAFKA_PRODUCER_CLIENT_ID:order-service-producer}
      acks: all
      retries: ${ORDER_KAFKA_PRODUCER_RETRIES:3}
      batch-size: ${ORDER_KAFKA_BATCH_SIZE:16384}
      buffer-memory: ${ORDER_KAFKA_BUFFER_MEMORY:33554432}
      compression-type: ${ORDER_KAFKA_COMPRESSION_TYPE:snappy}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

      properties:
        spring.json.add.type.headers: false
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
        delivery.timeout.ms: ${ORDER_KAFKA_DELIVERY_TIMEOUT_MS:120000}
        request.timeout.ms: ${ORDER_KAFKA_REQUEST_TIMEOUT_MS:30000}
        linger.ms: ${ORDER_KAFKA_LINGER_MS:5}

grpc:
  server:
    enabled: false

  clients:
    inventory:
      host: ${INVENTORY_GRPC_HOST:localhost}
      port: ${INVENTORY_GRPC_PORT:9091}
      deadline-ms: ${INVENTORY_GRPC_DEADLINE_MS:8000}
      plaintext: ${INVENTORY_GRPC_PLAINTEXT:true}

logging:
  level:
    root: INFO
    com.ecommerce.order: INFO
    org.springframework.kafka: INFO
    org.apache.kafka: WARN
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

order:
  default-currency: ${ORDER_DEFAULT_CURRENCY:INR}
