message: Payment Service DEV Environment

server:
  port: ${PAYMENT_SERVICE_PORT:8087}
  shutdown: graceful

spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5433}/${PAYMENT_DB_NAME:payment_db}
    username: ${POSTGRES_USER:ecommerce_user}
    password: ${POSTGRES_PASSWORD:ecommerce_password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

grpc:
  server:
    enabled: false
    port: ${PAYMENT_GRPC_PORT:9092}

payment:
  provider:
    active: ${PAYMENT_PROVIDER_ACTIVE:STRIPE}
    mode: ${PAYMENT_PROVIDER_MODE:sandbox}

    sandbox:
      enabled: ${PAYMENT_SANDBOX_ENABLED:false}

    stripe:
      enabled: ${STRIPE_ENABLED:true}
      api-key: "{cipher}afad22320bb1a7c402b5a9e34aaac5613b7db19928a52242f4b6553bad60e62be1844b7a82e0626128005faea2bf7ba97060c19f11974a9c9bbff8fa0e6a87e0ee4bd665ef912af63d035a54c8a6d267643a8f91d210fd112ac9e3518032b506247a054cc6233674b2e5fc30d34c43df83b763d5e45a51266885757582c0cd27"
      webhook-secret: "{cipher}d97b0f53777827cd94e61949dac35c8f48722183366bb4093c600b49539f7546584b4a16a6e1a7a734308b0ed4999a199edba15d6951f63a2a5c22f6c0f53f8de7502c2f65d1c3c186037c3a9f1b0b12493dc4db7c34701774439636bcb455a4"
      timeout-ms: ${STRIPE_TIMEOUT_MS:5000}

    razorpay:
      enabled: ${RAZORPAY_ENABLED:false}
      key-id: ${RAZORPAY_KEY_ID:}
      key-secret: ${RAZORPAY_KEY_SECRET:}
      webhook-secret: ${RAZORPAY_WEBHOOK_SECRET:}
      timeout-ms: ${RAZORPAY_TIMEOUT_MS:5000}

  checkout:
    success-url: "${PAYMENT_CHECKOUT_SUCCESS_URL:http://localhost:8087/public/payments/success?orderId={ORDER_ID}}"
    cancel-url: "${PAYMENT_CHECKOUT_CANCEL_URL:http://localhost:8087/public/payments/cancel?orderId={ORDER_ID}}"

  idempotency:
    key-prefix: ${PAYMENT_IDEMPOTENCY_KEY_PREFIX:payment}

logging:
  level:
    root: INFO
    com.ecommerce.payment: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
