message: Product Service PROD Environment

server:
  port: ${SERVER_PORT:8082}
  shutdown: graceful

spring:
  application.name: product-service
  data:
    mongodb:
      uri: ${PRODUCT_MONGODB_URI}
      database: ${PRODUCT_MONGODB_DATABASE:product_db}
