message: Cart Service STAGE Environment

server:
  port: ${SERVER_PORT:8085}
  shutdown: graceful

spring:
  application:
    name: cart-service
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
      username: ${REDIS_USERNAME:}
      password: ${REDIS_PASSWORD}
      ssl.enabled: ${REDIS_SSL_ENABLED:true}

cart:
  customer:
    ttl: ${CART_CUSTOMER_TTL:7d}
  guest:
    ttl: ${CART_GUEST_TTL:30d}

logging:
  level:
    root: INFO
    com.ecommerce.cart: INFO
